"""empty message

Revision ID: 71c0b14b79e8
Revises: e80a1015af2e
Create Date: 2021-11-20 11:38:23.115250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c0b14b79e8'
down_revision = 'e80a1015af2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'owners')
    op.drop_column('posts', 'technologies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('technologies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('owners', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
